# Generated by Django 3.2.3 on 2022-12-28 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='News_rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(choices=[('Scrap', 'Scrap'), ('HRC', 'HRC'), ('STLD', 'STLD'), ('RS', 'RS'), ('CLF', 'CLF'), ('TX', 'TX'), ('GGB', 'GGB'), ('X', 'X'), ('CMC', 'CMC'), ('TS', 'TS'), ('VK.PA', 'VK.PA'), ('TMST', 'TMST'), ('MT', 'MT'), ('PKX', 'PKX'), ('NUE', 'NUE'), ('RIO', 'RIO'), ('VALE', 'VALE'), ('SXC', 'SXC'), ('BHP', 'BHP'), ('HO=F', 'HO=F'), ('RB=F', 'RB=F'), ('coal', 'coal'), ('NWPX', 'NWPX'), ('TKA.DE', 'TKA.DE'), ('SZG.DE', 'SZG.DE'), ('Nippon', 'Nippon'), ('JFE', 'JFE'), ('iron', 'iron'), ('ULSD', 'ULSD'), ('BADI', 'BADI'), ('Truck', 'Truck'), ('CassFreight', 'CassFreight'), ('AllGrade', 'AllGrade'), ('Ardmore', 'Ardmore'), ('Arkoma', 'Arkoma'), ('Barnett', 'Barnett'), ('Cana', 'Cana'), ('Niobrara', 'Niobrara'), ('Ford', 'Ford'), ('Granite', 'Granite'), ('Haynesville', 'Haynesville'), ('Marcellus', 'Marcellus'), ('Mississippian', 'Mississippian'), ('Permian', 'Permian'), ('Utica', 'Utica'), ('Williston', 'Williston'), ('Anadarko_DUC', 'Anadarko_DUC'), ('Appalachia_DUC', 'Appalachia_DUC'), ('Bakken_DUC', 'Bakken_DUC'), ('Eagle_DUC', 'Eagle_DUC'), ('Haynesville_DUC', 'Haynesville_DUC'), ('Niobrara_DUC', 'Niobrara_DUC'), ('Permian_DUC', 'Permian_DUC'), ('raw material index', 'raw material index'), ('pipe manufacturing', 'pipe manufacturing'), ('steel manufacturing', 'steel manufacturing'), ('iron ore mining', 'iron ore mining'), ('fuel', 'fuel'), ('transportation', 'transportation'), ('RC_index', 'RC_index'), ('DPR_DUC', 'DPR_DUC')], default='', max_length=20)),
                ('relevance_level_tab', models.IntegerField(default='99')),
                ('on_landing_page', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('relevance_level_landing_page', models.IntegerField(default='99')),
                ('title', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('website', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.TextField(blank=True, max_length=500)),
                ('archive', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1)),
                ('exp_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Overriding News',
            },
        ),
        migrations.AddField(
            model_name='customer_table',
            name='first_installed_vr',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer_table',
            name='terms_vr',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='version_info',
            name='terms_vr',
            field=models.CharField(default='', max_length=40),
        ),
    ]
