# Generated by Django 3.2.3 on 2023-01-22 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texile_app', '0002_auto_20221228_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='y_data_hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=300)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
