# Generated by Django 3.2.3 on 2023-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texile_app', '0003_y_data_hourly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='y_data_hourly',
            name='created_time',
        ),
        migrations.AddField(
            model_name='y_data_hourly',
            name='chart',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='y_data_hourly',
            name='update_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='y_data_hourly',
            name='data',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='y_data_hourly',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
