# Generated by Django 3.2.3 on 2023-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texile_app', '0005_auto_20230122_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='y_data_hourly',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='y_data_hourly',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
